site_name: Mockler Lab
site_url: https://mocklerlab.org
site_description: "Mockler Lab memorial website"
site_author: "Mockler Lab"
repo_url: https://github.com/danforthcenter/mocklerlab
copyright: "Copyright 2025, Donald Danforth Plant Science Center"
theme:
 name: material
 logo: imgs/logo.png

nav:
  - Home: index.md
