site_name: Mockler Lab
site_url: https://mocklerlab.org
site_description: "Mockler Lab memorial website"
site_author: "Mockler Lab"
repo_url: https://github.com/mocklerlab
copyright: "Copyright 2025, Donald Danforth Plant Science Center"
theme:
 name: bootstrap4
 next_previous: false

plugins:
  - bootstrap4-blockquotes
  - bootstrap4-tables

nav:
  - Home: index.md
